#pragma config(Sensor, in1,    LineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    Potatometer,    sensorPotentiometer)
#pragma config(Sensor, in3,    LightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  LimitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  BumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  Sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl11, GreenLight,     sensorLEDtoVCC)
#pragma config(Motor,  port1,           Flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
turnLEDOn(GreenLight);
untilPotentiometerGreaterThan(2048, Potatometer); //Turn on the greenLED until the potentiometer is at a value greater than 2048.
turnLEDOff(GreenLight); //Turn off the greenLED.
startMotor(leftMotor, 63); //Turn on the leftMotor at half power until the potentiometer is at a value of less than 2048.
untilPotentiometerLessThan(2048, Potatometer);
stopMotor(leftMotor);
}
